package com.wlh.study.genpj.mainpj.model;

public class Mainpj {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainpj.id
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainpj.name
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainpj.id
     *
     * @return the value of mainpj.id
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainpj.id
     *
     * @param id the value for mainpj.id
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainpj.name
     *
     * @return the value of mainpj.name
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainpj.name
     *
     * @param name the value for mainpj.name
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}