package com.wlh.study.genpj.mainpj.mapper;

import com.wlh.study.genpj.mainpj.model.Mainpj;
import com.wlh.study.genpj.mainpj.model.MainpjExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MainpjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mainpj
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    long countByExample(MainpjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mainpj
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    int deleteByExample(MainpjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mainpj
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mainpj
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    int insert(Mainpj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mainpj
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    int insertSelective(Mainpj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mainpj
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    List<Mainpj> selectByExample(MainpjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mainpj
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    Mainpj selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mainpj
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") Mainpj record, @Param("example") MainpjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mainpj
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    int updateByExample(@Param("record") Mainpj record, @Param("example") MainpjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mainpj
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    int updateByPrimaryKeySelective(Mainpj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mainpj
     *
     * @mbg.generated Tue Dec 04 23:40:34 CST 2018
     */
    int updateByPrimaryKey(Mainpj record);
}